services:
  atuin:
    user: "1000:1000"
    restart: always
    image: ghcr.io/atuinsh/atuin:18.10.0
    command: server start
    volumes:
      - "./config:/config"
    ports:
      # host:container
      - "51234:8888"   # change 51234 to any high port you prefer
    environment:
      ATUIN_HOST: "0.0.0.0"
      # Optional: only set this if you *also* want to change the container's internal port.
      # If you set this, then also change the mapping to "51234:<same_port>".
      # ATUIN_PORT: "8888"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@db/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
    depends_on:
      - db
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - "./database:/var/lib/postgresql/data/"
    ports:
      - "55432:5432"  # host:container
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
